language: android
jdk: oraclejdk8
before_install:
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - nvm install 4.1.1
  - nvm use 4.1.1
  - npm i -g npm@3
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install mongodb-org-server
  - git clone https://github.com/HabitRPG/habitrpg.git ../habitrpg
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 2; done
  - cd ../habitrpg && cp config.json.example config.json && npm install
  - npm start &
  - until nc -z localhost 3000; do echo Waiting for Habitica Server; sleep 2; done
  - cd -
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.2

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17
script:
    - cp habitica.properties.travis habitica.properties
    - cp habitica.resources.example habitica.resources
    - cp Habitica/google-services.json.example Habitica/google-services.json
    - ./gradlew assembleDebug
    - ./gradlew testDebugUnitTest --info
